(function () {
    window._CCSettings = {
        platform: "wechatgame",
        groupList: ["default"],
        collisionMatrix: [[!0]],
        rawAssets: {
            assets: {
                "047Sy5ThxNQriI2XIRroSX": ["_TrickyGame/_Texture/_Add/askHelp.png", 0],
                "94Xi+g6UZMIYq8/X3zdAdb": ["_TrickyGame/_Texture/_Add/hint.png", 0],
                "87YkM1jG9ICrrXfmGMNqeV": ["_TrickyGame/_Texture/_Add/levels.png", 0],
                b6U8zmDg1Mc6YNU7V4aTux: ["_TrickyGame/_Texture/_Add/shareBtn.png", 0],
                "0bgmwcDGROcaatZPu4TvsL": ["_TrickyGame/_Texture/_Level/Level01/daxiang.png", 0],
                "0e1gP3lnJHOYHk32CGk2CC": ["_TrickyGame/_Texture/_Level/Level01/laos.png", 0],
                "73LYN5cytO+7zVQqCce+IA": ["_TrickyGame/_Texture/_Level/Level01/niu.png", 0],
                "3d1iotjm1Dk69yzNEXA1Sz": ["_TrickyGame/_Texture/_Level/Level01/shizi.png", 0],
                "909acmNXlMO5q9Dms7u3vw": ["_TrickyGame/_Texture/_Level/Level01/tuzi.png", 0],
                "99uKeurspP0axX/GPDwQ46": ["_TrickyGame/_Texture/_Level/Level02/bbt.png", 0],
                e3syerO1ZCPrE8YMZOaCnv: ["_TrickyGame/_Texture/_Level/Level02/deng.png", 0],
                "90OGxYY/JENqbmBVfGL1GK": ["_TrickyGame/_Texture/_Level/Level02/san.png", 0],
                "048CkQ5jpEcqg5zX8YJP7v": ["_TrickyGame/_Texture/_Level/Level02/shui.png", 0],
                "80xZ2am9xHnq/FLp56Sh9q": ["_TrickyGame/_Texture/_Level/Level03/tuz1.png", 0],
                "924+ygXClJTKpwq5L3eJH4": ["_TrickyGame/_Texture/_Level/Level03/tuz2.png", 0],
                "8aTf6NjXROUK1OpZVmpTUs": ["_TrickyGame/_Texture/_Level/Level05/X.png", 0],
                c3NwaO3GdDnqXA0gkyUcde: ["_TrickyGame/_Texture/_Level/Level05/XX.png", 0],
                "9cjD3fiBlOQ5BrZi+OrUNH": ["_TrickyGame/_Texture/_Level/Level05/pjia.png", 0],
                "73jHTkHvRMbqNG1jp+G2Bz": ["_TrickyGame/_Texture/_Level/Level06/s.png", 0],
                efhNQe46NE2pSBdjPgQ5JX: ["_TrickyGame/_Texture/_Level/Level06/x.png", 0],
                "a6BOsvnGhHWJ7V3YAS6+Ql": ["_TrickyGame/_Texture/_Level/Level06/y.png", 0],
                "3c1E9gE3BGY6gPvP+O0PRG": ["_TrickyGame/_Texture/_Level/Level06/z.png", 0],
                "5dMnlvu55ErqZfnvur4Vxd": ["_TrickyGame/_Texture/_Level/Level08/ann.png", 0],
                c7Q9G6AkVJ2ppA6p4IY46L: ["_TrickyGame/_Texture/_Level/Level08/dpx.png", 0],
                "3fYUF6505BGJriRRKO/dJB": ["_TrickyGame/_Texture/_Level/Level08/dt.png", 0],
                "cc6uWgKuZA5KuSk4l1shk/": ["_TrickyGame/_Texture/_Level/Level09/bz.png", 0],
                "73GEzIKaRGE4b534PwxAfK": ["_TrickyGame/_Texture/_Level/Level09/st.png", 0],
                "40Q9yP99dL5pGgdvuRg2q5": ["_TrickyGame/_Texture/_Level/Level09/sz.png", 0],
                "0d4kn6y81HN5lc0lISvRQE": ["_TrickyGame/_Texture/_Level/Level09/szz.png", 0],
                bbgr2BtkVCmJRy2RJKkYsP: ["_TrickyGame/_Texture/_Level/Level09/wz.png", 0],
                "12zHjmiy1JuL0gphPyWU+S": ["_TrickyGame/_Texture/_Level/Level09/xc.png", 0],
                "9ang6LSotB+a1pIN/KRRMH": ["_TrickyGame/_Texture/_Level/Level10/ht.png", 0],
                "0eWcfS1HpIzJrbbaaw4Su4": ["_TrickyGame/_Texture/_Level/Level10/twj.png", 0],
                aeVd2Qp5hG1Y6ddOLOXcli: ["_TrickyGame/_Texture/_Level/Level11/passBtn.png", 0],
                "1amkrb2OFIUrWnJy5SEnkQ": ["_TrickyGame/_Texture/_Level/Level12/1.png", 0],
                "18/ARFnt1Bw7rtmyNppb3V": ["_TrickyGame/_Texture/_Level/Level12/2.png", 0],
                "5bjm6SO3ZL+I32xvaI/CCt": ["_TrickyGame/_Texture/_Level/Level12/3.png", 0],
                d9JJQYsKJIDLhshLzkOrng: ["_TrickyGame/_Texture/_Level/Level12/4.png", 0],
                "c1q6EUxBZN8bXUOCjiIJ+t": ["_TrickyGame/_Texture/_Level/Level12/5.png", 0],
                "47H9uxVhNMELI8Ws+Imf+z": ["_TrickyGame/_Texture/_Level/Level12/ZZ.png", 0],
                "57x7HAZ2JOhqJ/mjK46ZsB": ["_TrickyGame/_Texture/_Level/Level12/xgn.png", 0],
                "45JBkb9M1I1ZDN+gB/2pSC": ["_TrickyGame/_Texture/_Level/Level13/BS.png", 0],
                "49RqT6h/hE7rZcV5lFWAa2": ["_TrickyGame/_Texture/_Level/Level13/BS2.png", 0],
                d6vSwMXkpIEJ8y1p2Is44U: ["_TrickyGame/_Texture/_Level/Level13/men.png", 0],
                "0821GkCQhHbZuH09iMbyYI": ["_TrickyGame/_Texture/_Level/Level13/smallHuang.png", 0],
                "96GS7omnpIipMEb1AzlG8y": ["_TrickyGame/_Texture/_Level/Level15/shui.png", 0],
                e6xOy2dEVNp5rPfXl04V3v: ["_TrickyGame/_Texture/_Level/Level16/qqiu.png", 0],
                "78XnPEXupDipJuzQTeYXj6": ["_TrickyGame/_Texture/_Level/Level18/ac.png", 0],
                c0WIs0paBDS7aWf0crZeQ1: ["_TrickyGame/_Texture/_Level/Level18/jia.png", 0],
                abTkJnjHBPQa9pAaZYpnI0: ["_TrickyGame/_Texture/_Level/Level18/jian.png", 0],
                c0po7AlfZLF5PeQ5xYlTFV: ["_TrickyGame/_Texture/_Level/Level18/qr.png", 0],
                "b5Ii708jtCeZ8C66BT+Xng": ["_TrickyGame/_Texture/_Level/Level19/ay518.png", 0],
                "dccmR9URtK3aU/N086lgrS": ["_TrickyGame/_Texture/_Level/Level19/11.png", 0],
                "d40vdvD+tGl4gfNj4nyxb3": ["_TrickyGame/_Texture/_Level/Level19/5.png", 0],
                bfVYy0X0NMkIxXRfh2YnNM: ["_TrickyGame/_Texture/_Level/Level19/9.png", 0],
                "57SxnWGlNAVL6KODxP3mI6": ["_TrickyGame/_Texture/_Level/Level19/=.png", 0],
                "6c5UOrhrhMOJ5nzKAUEPF+": ["_TrickyGame/_Texture/_Level/Level20/BK.png", 0],
                "457nDXSw9Jk4sg4pFUieHI": ["_TrickyGame/_Texture/_Level/Level20/bai.png", 0],
                "18SFcl3wZH34E+GcD5mIR/": ["_TrickyGame/_Texture/_Level/Level22/huis.png", 0],
                "1fcEyFhVlN3Yasir4TciDd": ["_TrickyGame/_Texture/_Level/Level22/lbs.png", 0],
                "f4JvPiettFI6ZdlKXbMcg+": ["_TrickyGame/_Texture/_Level/Level22/ls.png", 0],
                "05k6XcpvJDQIQL6WrxIfiU": ["_TrickyGame/_Texture/_Level/Level22/yg.png", 0],
                "3eLvwNqnlD+aHK1lWSi4GL": ["_TrickyGame/_Texture/_Level/Level23/HD.png", 0],
                c33rkYVTZOVLWWL9zbLmDe: ["_TrickyGame/_Texture/_Level/Level24/clock.png", 0],
                "39FXtJbcdEuKfvU2vKOMC6": ["_TrickyGame/_Texture/_Level/Level25/YF.png", 0],
                "f5d//YGwBCTrnQfErRkxqc": ["_TrickyGame/_Texture/_Level/Level25/baiyun.png", 0],
                "18Nzkyf8hFQJeW0sUyLUP7": ["_TrickyGame/_Texture/_Level/Level25/wuyun.png", 0],
                d8YoKJK1xK24UitL9qAb1u: ["_TrickyGame/_Texture/_Level/Level25/yu.png", 0],
                "94WMxnISJK0phoyl2aPF2o": ["_TrickyGame/_Texture/_Level/Level25/zw.png", 0],
                "3cMx9J8RtHcoyaYa7Su/ZP": ["_TrickyGame/_Texture/_Level/Level26/AN.png", 0],
                "e7ytZYf4lIvYLq/nH3eYFj": ["_TrickyGame/_Texture/_Level/Level26/ANN.png", 0],
                caXQj0v4RFnrfxeIngZzXx: ["_TrickyGame/_Texture/_Level/Level27/anniu.png", 0],
                c25GWIE8tDjow11nkZAYrj: ["_TrickyGame/_Texture/_Level/Level27/dnao.png", 0],
                "4fmx/imR1GRaH+UazZX8O6": ["_TrickyGame/_Texture/_Level/Level27/zw.png", 0],
                "f56MopYmJNNY+MImVjg2DH": ["_TrickyGame/_Texture/_Level/Level27/zz.png", 0],
                d0FFzPYW9Ph53YVUZ186SP: ["_TrickyGame/_Texture/_Level/Level28/11.png", 0],
                "74nLz3qKdE7IUCObmMs3zH": ["_TrickyGame/_Texture/_Level/Level28/12.png", 0],
                "86LBGaW2VBxpk+xzc58K60": ["_TrickyGame/_Texture/_Level/Level28/13.png", 0],
                "09R7e/gp1OnJs8hfpJN/2d": ["_TrickyGame/_Texture/_Level/Level28/15.png", 0],
                "03hhwEQQ9HNIfSxoqHPrOc": ["_TrickyGame/_Texture/_Level/Level28/7.png", 0],
                "49tc2spMFD7Ytkfqz5VWd9": ["_TrickyGame/_Texture/_Level/Level28/qz.png", 0],
                "38qbuM+cZL0KhILgqLM8/o": ["_TrickyGame/_Texture/_Level/Level29/JB(1).png", 0],
                b6uRWpfmdEeJbdcnFlikBU: ["_TrickyGame/_Texture/_Level/Level29/MT.png", 0],
                "f8odeqF+hGI7vDgogFrbjn": ["_TrickyGame/_Texture/_Level/Level29/YF.png", 0],
                "18lKPwOVpN06e30fD8wJXm": ["_TrickyGame/_Texture/_Level/Level29/huo.png", 0],
                "fdFqRTL3RPY5R+3qUbjRAk": ["_TrickyGame/_Texture/_Level/_ForAll/cuo.png", 0],
                acI6mP2eRGZrLffkq3z8iP: ["_TrickyGame/_Texture/_Level/_ForAll/dui.png", 0],
                "01zKIMFb5JaK8mbbts55f5": ["_TrickyGame/_Texture/_Promo/promo02.png", 0],
                "50PE0cVzZFrZZYTwYXywNA": ["_TrickyGame/_Texture/_UI/back.png", 0],
                "5dhIXs24RAFpMKhPMbVF85": ["_TrickyGame/_Texture/_UI/bg1.png", 0],
                acTlnsAxlLl5gMf5YYy2Gr: ["_TrickyGame/_Texture/_UI/bg2.png", 0],
                "8b4N6ZosNEcLDlSBWUzKBS": ["_TrickyGame/_Texture/_UI/bgFrame.png", 0],
                "2erj2BfDRBbrsWLileZAPn": ["_TrickyGame/_Texture/_UI/goHome.png", 0],
                b98SSWsPRNh5ItY8gXlGEc: ["_TrickyGame/_Texture/_UI/haod.png", 0],
                "861B1t9mpNv6qDJe0e3l4O": ["_TrickyGame/_Texture/_UI/jus.png", 0],
                "75MiScB2RBK4/N6Hnnao+Z": ["_TrickyGame/_Texture/_UI/levelBtn_off.png", 0],
                "59+qNDeFBM36m2Lkji/PlI": ["_TrickyGame/_Texture/_UI/levelBtn_on.png", 0],
                "1e72UFAClEBrD4e8MJ1KpW": ["_TrickyGame/_Texture/_UI/logo.png", 0],
                "348fMbVh9GLIkbIKtFB3HF": ["_TrickyGame/_Texture/_UI/nextBtn.png", 0],
                ec4FL4taFK3r5OXnBsEJUK: ["_TrickyGame/_Texture/_UI/passedBgFrame.png", 0],
                "15/Sjne5lJzrgaAWoRyTU4": ["_TrickyGame/_Texture/_UI/startBtn.png", 0],
                "22/QUJR7lLc6ARnK1zELYo": ["_TrickyGame/_Texture/_UI/title.png", 0],
                "e8Pk+kNnVOKJPk/1ADZnVC": ["_TrickyGame/_Texture/_UI/toMenu.png", 0],
                fdEmFlreJMJ7OEy2iSDsUG: ["_TrickyGame/_Texture/__ForAll/alphaBg.png", 0],
                d9iXTfylVIX7BbM3I7XHW7: ["_TrickyGame/_Texture/__ForAll/transparentBg.png", 0],
                beDXkSNb1Mn5naSQQESmsI: ["resources/promo.json", 1]
            }
        },
        assetTypes: ["cc.Texture2D", "cc.RawAsset"],
        launchScene: "db://assets/_TrickyGame/_Scene/TrickyGame.fire",
        scenes: [{
            url: "db://assets/_TrickyGame/_Scene/TrickyGame.fire",
            uuid: 0
        }],
        packedAssets: {
            "012eb935a": ["0036lmpKFAdZAtKYE9bhsY", "02PEoCaBZNWpCKBIR2xNoN", "03lztlHp5I46bEqZ/oeBoy", "0bqRumi8FD25F68EY7JX5a", "0dfjunyN9LFJvWMbzua9Tz", "0exMcGxQ9PXIv1rLKa+kDm", "0fZFS4YnlO7b71eUZVxeuI", "0fkAitsd1EjoponxhiIO2c", "10rsqUHdtNS5dZ88FwVbjX", "11YrC38IlJJbvM5uv2hezZ", "135QumovpH34xD1gndV84t", "137/sDxWNCg6rQMg/tEg+S", "15m4TWzGJBbYsfLcJc65td", "17DEN/J+9PoZA65BMl4cMf", "17smHvc7BCso707BQjtzaI", "1axsul5jhAKrSOacvX4wd3", "1bsa94Pj1CWbOucAptSNmn", "1cy52erpdKkqB0AVhuvto1", "1eOX2VYgpPr5rMQW8F0ka3", "20gi0t92dBRbhnpcF7Optv", "21viwgYSJLpKgXa88J1sMa", "21xyHGP59OfLzSRYha/YSY", "23hrY5Y+ZAD5gKEOMcVSd9", "253UQEomBGQ7St7favwyAT", "27xDFAuIFOQIb2HgA+CRSG", "2axtheWX5GpL1pnY2z34Ig", "2a+eYxJLpHKbd2O7NdKEIu", "2dAWS1U4pCBYahrVTenv3g", "2dAn6Cvj9JDIBJUyA4b9aU", "30kSRNN2dLaZrLvagTdny6", "31Kb/nQdZDKLJQvp1SmbPc", "31p3DO0lhKspgyRmvmqZQQ", "31r/EUqalKJbqNap03i7sM", "3176sWWrZD4LqO7ijNEry2", "34dQYSsI9DiaU55dgnSu6M", "35QOaTWmxFQLuOmVXIVatH", "37Sm1NzEtE4IzkideddIZn", "3973lqWdxJRKT8xAQbOgks", "3du1a1j+VN5a+GKFLzBPwf", "42xVgMdOdMQbeF2QDVJzCC", "44wu7FmSVJ5Kpw3GvH4Sq+", "45kbKYOpZDP4WKQWjsyrFf", "450F8rKnBBV5XYAaGQ/n12", "49bR50arNJQa+c33m3wGc+", "49lOvddTlN67L7fIms3QUv", "4aRZD8gUhHi5GyHqtKi/QC", "4amOdjYNlLmrv9qxqpW7qv", "4e1ODlryNIPoSjPHyzstcw", "4e8az5nD5A9b7igLzcHyNt", "4fk9ic1yJOFYOmXJUv2A5I", "50dXZVBI5FW5jCSWdi2T85", "5139pu1sJE3J6xaryVpdXF", "55GENEEYZNebtN1WHrmmTn", "5bx2JS7xlCMrd5Wr4uXCeV", "5fbcNYSRdHeLTB4iDdu7m7", "61ahcVTq1AHrjLjTCI3EVQ", "66hejF3RBJiL28hoUJlwwo", "6aosjn3gFM14H9BDJplBjz", "6dfHDckMJH7oYQcJx2wHK4", "6efEsyYk5G8rmaFbKkKGRD", "6egOJSRnZIHq0MSFhOgWXm", "6e15nxFQxEKbwRs4KK4tsY", "71nNFAfGZKTLXG9diEYH8Y", "72MszwxCFK1oGzlCf+imVk", "74X6nztdxOgYoR0wj4Ebxc", "774BMQIxBO86p03UM3u2GT", "78nheY7BlNe7i/ewYK5n11", "789gdcYqpHmqrRju8KjuHL", "7a6g5l6HlNo4vsgulwZKc5", "7cxDUSaWdPXpzlFJNYIfnI", "7dOW/6KodNi6k7Nps0SvJw", "80QlmnDSFP/6iaScYfBY3s", 0, "84EkxFGnJKdZSKKfsg2sUc", "87p3+NOvJOGI+cuBbBvacW", "8ddD9RuC5OYqmhsQsAhyEE", "8ddOOL0QJH4aXcVc1vnFBg", "90KGS0KNdJ/5eDh8imvwVw", "917GNJ9bRDSr/dnjzHDUV8", "93UeZCHYFMxreAX71PJRmm", "937rvcwrRPh6aSsQI/y/hs", "94GjdWYqNPA4zMMBLEvF6k", "94N7CEAiBL7Z1aGGfjZbXp", "98QlaHoQlAjb7ALR2SkbTD", "9alTzCoI5J9ILktyVHA28X", "9bcBYUHodGxaCvNAb8B0b0", "a0OzxauVxL56sXOJYqtjjS", "a1xVYXzNlMkZndSWSYiwbM", "a3oncG4fNPPabbzRuvXKuQ", "a5FPQgn/FB2aCo7/qCCgq6", "a6SgvvDb9H6psHnm/n5r2c", "a7E0N+8EhBYr+1jj3e0RlP", "a7oUDLqEBFoq4RLQha3JhF", "a8LzPVgDlCsYxtS9avallm", "a8dfoRNhZAN4cftL+z/FbE", "ae6qd5whxMTKtx8lwGLD5m", "b1KSPd9CJOaY0zXN0VlY0T", "b183ZrI7FCAZmMhUrjjLdl", "b2wKZ7u/hBs7+DS01kgSAS", "b8I6JEemhIj62oia5wOhE0", "ba34uInktHL7bf8TkBxboL", "bcj+podJFMd5L6xPYelkpR", "c03jHJTfdNW44vydlYQaj3", "c1qUcTOBZOMYsrd4YgZu/J", "c2J9j1MBRPaaaBINtVvQsx", "c3j2V3cRhJdp+KyxQfOcD/", "c3vXjptIdDQ7g7N52qPX9E", "c9IaElCUtFZptq+KCEMGL7", "c9sYQq9kRBEpVZnSFC7dZe", "canQ8nLwpAR4DZYzqyuKyM", "ca1zD2+blFh4H26g8rKqGB", "ccCH18WHFKK4COPtTpbGUE", "cdjSYeNkpAcKwwUZkCglI0", "cfCH6IcAZB1pdCZJpMnHYr", "d2cen1SHtAHq9TuP0+jVRN", "d28DNTwpFHu7XGsum4Hnqm", "d3ZFk26BdAz7eSQTFPGLRD", "d5deUYa+9IJIagXqjFZZ32", "d6wsIPD9tDarXaxc79E545", "d7Qf13yotPcLPgNy2/Bngk", "d7b74ak3JL+62dDg5v7899", "d7ghFWTPpForcLeaA7lB/u", "d7raD8WSNMz73JKbj3PodS", "d8cAhNyghBeZ2ZdsMGyody", "dbNV/2iKpKGLIrpbT8AnvH", "de5EK3gL9AObPIc1iTwJXg", "dflfwOHQxMB58NTffLAGDq", "e9xxmKwsBBropI8PwVNASk", "efOC1fTZdK+Z1v9l6edUtq", "f4YcncbOZHqYbZbqrLhj2J", "f7+74I1iJMsrowj0gOhwQi", "f8vQGVof1JaovBl6+dl+uV", "f88mZ4zTNODYHYrgCU0JDM", "fbq0Z4/cRPRoz05IMMdXBZ", "fd2gS2NP5A9rPx7qlz5FXT", "feaOnNOhhEA4DgQgT8TMiJ"]
        },
        orientation: "",
        uuids: ["83nTf7JQpPsr8lh58SRuFq"],
        md5AssetsMap: {
            "01/012eb935a.json": "089be",
            "assets/_TrickyGame/_Texture/__ForAll/alphaBg.png": "64489",
            "assets/_TrickyGame/_Texture/__ForAll/transparentBg.png": "03a17",
            "assets/_TrickyGame/_Texture/_Add/askHelp.png": "de5ba",
            "assets/_TrickyGame/_Texture/_Add/hint.png": "fdb80",
            "assets/_TrickyGame/_Texture/_Add/levels.png": "51bdf",
            "assets/_TrickyGame/_Texture/_Add/shareBtn.png": "08aa1",
            "assets/_TrickyGame/_Texture/_Level/_ForAll/cuo.png": "cc8ef",
            "assets/_TrickyGame/_Texture/_Level/_ForAll/dui.png": "06891",
            "assets/_TrickyGame/_Texture/_Level/Level01/daxiang.png": "0015b",
            "assets/_TrickyGame/_Texture/_Level/Level01/laos.png": "6255f",
            "assets/_TrickyGame/_Texture/_Level/Level01/niu.png": "4e403",
            "assets/_TrickyGame/_Texture/_Level/Level01/shizi.png": "09458",
            "assets/_TrickyGame/_Texture/_Level/Level01/tuzi.png": "c47eb",
            "assets/_TrickyGame/_Texture/_Level/Level02/bbt.png": "c047e",
            "assets/_TrickyGame/_Texture/_Level/Level02/deng.png": "a2133",
            "assets/_TrickyGame/_Texture/_Level/Level02/san.png": "5d8da",
            "assets/_TrickyGame/_Texture/_Level/Level02/shui.png": "c3251",
            "assets/_TrickyGame/_Texture/_Level/Level03/tuz1.png": "3926e",
            "assets/_TrickyGame/_Texture/_Level/Level03/tuz2.png": "b7384",
            "assets/_TrickyGame/_Texture/_Level/Level05/pjia.png": "24dc3",
            "assets/_TrickyGame/_Texture/_Level/Level05/X.png": "95b03",
            "assets/_TrickyGame/_Texture/_Level/Level05/XX.png": "94945",
            "assets/_TrickyGame/_Texture/_Level/Level06/s.png": "980f5",
            "assets/_TrickyGame/_Texture/_Level/Level06/x.png": "8de33",
            "assets/_TrickyGame/_Texture/_Level/Level06/y.png": "0656d",
            "assets/_TrickyGame/_Texture/_Level/Level06/z.png": "9c28a",
            "assets/_TrickyGame/_Texture/_Level/Level08/ann.png": "8801a",
            "assets/_TrickyGame/_Texture/_Level/Level08/dpx.png": "911da",
            "assets/_TrickyGame/_Texture/_Level/Level08/dt.png": "88c86",
            "assets/_TrickyGame/_Texture/_Level/Level09/bz.png": "f556a",
            "assets/_TrickyGame/_Texture/_Level/Level09/st.png": "a7cc4",
            "assets/_TrickyGame/_Texture/_Level/Level09/sz.png": "01ee3",
            "assets/_TrickyGame/_Texture/_Level/Level09/szz.png": "9fe8e",
            "assets/_TrickyGame/_Texture/_Level/Level09/wz.png": "8fa2f",
            "assets/_TrickyGame/_Texture/_Level/Level09/xc.png": "926bc",
            "assets/_TrickyGame/_Texture/_Level/Level10/ht.png": "dce8d",
            "assets/_TrickyGame/_Texture/_Level/Level10/twj.png": "5f899",
            "assets/_TrickyGame/_Texture/_Level/Level11/passBtn.png": "d7e25",
            "assets/_TrickyGame/_Texture/_Level/Level12/1.png": "c7d6f",
            "assets/_TrickyGame/_Texture/_Level/Level12/2.png": "b38c7",
            "assets/_TrickyGame/_Texture/_Level/Level12/3.png": "e149c",
            "assets/_TrickyGame/_Texture/_Level/Level12/4.png": "3d5e4",
            "assets/_TrickyGame/_Texture/_Level/Level12/5.png": "6b2c4",
            "assets/_TrickyGame/_Texture/_Level/Level12/xgn.png": "543b1",
            "assets/_TrickyGame/_Texture/_Level/Level12/ZZ.png": "b984d",
            "assets/_TrickyGame/_Texture/_Level/Level13/BS.png": "4eebd",
            "assets/_TrickyGame/_Texture/_Level/Level13/BS2.png": "6236a",
            "assets/_TrickyGame/_Texture/_Level/Level13/men.png": "a05e1",
            "assets/_TrickyGame/_Texture/_Level/Level13/smallHuang.png": "c6461",
            "assets/_TrickyGame/_Texture/_Level/Level15/shui.png": "5eb88",
            "assets/_TrickyGame/_Texture/_Level/Level16/qqiu.png": "ba6f7",
            "assets/_TrickyGame/_Texture/_Level/Level18/ac.png": "2e1f2",
            "assets/_TrickyGame/_Texture/_Level/Level18/jia.png": "9ebfa",
            "assets/_TrickyGame/_Texture/_Level/Level18/jian.png": "28051",
            "assets/_TrickyGame/_Texture/_Level/Level18/qr.png": "5db17",
            "assets/_TrickyGame/_Texture/_Level/Level19/ay518.png": "2fbb2",
            "assets/_TrickyGame/_Texture/_Level/Level19/=.png": "0df10",
            "assets/_TrickyGame/_Texture/_Level/Level19/11.png": "4a36b",
            "assets/_TrickyGame/_Texture/_Level/Level19/5.png": "0090f",
            "assets/_TrickyGame/_Texture/_Level/Level19/9.png": "a1396",
            "assets/_TrickyGame/_Texture/_Level/Level20/bai.png": "69394",
            "assets/_TrickyGame/_Texture/_Level/Level20/BK.png": "10dad",
            "assets/_TrickyGame/_Texture/_Level/Level22/huis.png": "b47b2",
            "assets/_TrickyGame/_Texture/_Level/Level22/lbs.png": "f1c05",
            "assets/_TrickyGame/_Texture/_Level/Level22/ls.png": "70d4a",
            "assets/_TrickyGame/_Texture/_Level/Level22/yg.png": "34d61",
            "assets/_TrickyGame/_Texture/_Level/Level23/HD.png": "00e35",
            "assets/_TrickyGame/_Texture/_Level/Level24/clock.png": "e364c",
            "assets/_TrickyGame/_Texture/_Level/Level25/baiyun.png": "05f4f",
            "assets/_TrickyGame/_Texture/_Level/Level25/wuyun.png": "f984f",
            "assets/_TrickyGame/_Texture/_Level/Level25/YF.png": "f7e3c",
            "assets/_TrickyGame/_Texture/_Level/Level25/yu.png": "2fcba",
            "assets/_TrickyGame/_Texture/_Level/Level25/zw.png": "bfe83",
            "assets/_TrickyGame/_Texture/_Level/Level26/AN.png": "01f75",
            "assets/_TrickyGame/_Texture/_Level/Level26/ANN.png": "b9f83",
            "assets/_TrickyGame/_Texture/_Level/Level27/anniu.png": "73229",
            "assets/_TrickyGame/_Texture/_Level/Level27/dnao.png": "97994",
            "assets/_TrickyGame/_Texture/_Level/Level27/zw.png": "f56b7",
            "assets/_TrickyGame/_Texture/_Level/Level27/zz.png": "c6214",
            "assets/_TrickyGame/_Texture/_Level/Level28/11.png": "e49bd",
            "assets/_TrickyGame/_Texture/_Level/Level28/12.png": "bb11d",
            "assets/_TrickyGame/_Texture/_Level/Level28/13.png": "326ad",
            "assets/_TrickyGame/_Texture/_Level/Level28/15.png": "b679f",
            "assets/_TrickyGame/_Texture/_Level/Level28/7.png": "c56a8",
            "assets/_TrickyGame/_Texture/_Level/Level28/qz.png": "1c780",
            "assets/_TrickyGame/_Texture/_Level/Level29/huo.png": "fefc0",
            "assets/_TrickyGame/_Texture/_Level/Level29/JB(1).png": "874f3",
            "assets/_TrickyGame/_Texture/_Level/Level29/MT.png": "24d2f",
            "assets/_TrickyGame/_Texture/_Level/Level29/YF.png": "7d0c5",
            "assets/_TrickyGame/_Texture/_Promo/promo02.png": "fa31b",
            "assets/_TrickyGame/_Texture/_UI/back.png": "234b0",
            "assets/_TrickyGame/_Texture/_UI/bg1.png": "be718",
            "assets/_TrickyGame/_Texture/_UI/bg2.png": "fef0a",
            "assets/_TrickyGame/_Texture/_UI/bgFrame.png": "e7c20",
            "assets/_TrickyGame/_Texture/_UI/goHome.png": "decd1",
            "assets/_TrickyGame/_Texture/_UI/haod.png": "3f24d",
            "assets/_TrickyGame/_Texture/_UI/jus.png": "923f5",
            "assets/_TrickyGame/_Texture/_UI/levelBtn_off.png": "7818c",
            "assets/_TrickyGame/_Texture/_UI/levelBtn_on.png": "ed22b",
            "assets/_TrickyGame/_Texture/_UI/logo.png": "24de9",
            "assets/_TrickyGame/_Texture/_UI/nextBtn.png": "718a4",
            "assets/_TrickyGame/_Texture/_UI/passedBgFrame.png": "f93ee",
            "assets/_TrickyGame/_Texture/_UI/startBtn.png": "6ad1d",
            "assets/_TrickyGame/_Texture/_UI/title.png": "6e2ea",
            "assets/_TrickyGame/_Texture/_UI/toMenu.png": "c7af1",
            "assets/resources/promo.json": "d88c6"
        }
    };
})();